server:
  servlet:
    encoding:
      force-response: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hospital
    username: test
    password: test
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true