server:
  servlet:
    encoding:
      force-response: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hospital
    username: test
    password: test
  jpa:
    hibernate:
      ddl-auto: update